import {Inter} from 'next/font/google'
import './global.css'
import {Providers} from "@/app/globalRedux/Provider";
import React from "react";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children, myRooms, navBar}: {
    children: React.ReactNode
    myRooms: React.ReactNode
    navBar: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${inter.className} lg:max-w-screen-lg md:max-w-screen-md w-full m-auto relative`}>
        <Providers>
            <div className={`bg-gray-200`}>
                {navBar}
                {children}
                {myRooms}
            </div>
        </Providers>
        </body>
        </html>
    )
}
