import {Inter} from 'next/font/google'
import './global.css'
import {Providers} from "@/app/_globalRedux/Provider";
import React from "react";
import Navbar from "@/app/_component/navbar/navbar";
import {Navigations} from "@/app/@navBar/page";

export type Navigations = {name:string,href:string}[]
const inter = Inter({subsets: ['latin']})
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children, myRooms}: {
    children: React.ReactNode
    myRooms: React.ReactNode
}) {
    const navigation:Navigations = [
        { name: 'Home', href: '/' },
        { name: 'Chat', href: '/chat' },
        { name: 'Room', href: '/room' },
        { name: 'Team', href: '/team' },
    ]

    return (
        <html lang="en">
        <body className={`${inter.className} lg:max-w-screen-lg md:max-w-screen-md w-full m-auto relative`}>
        <Providers>
            <div className={`bg-gray-200`}>
                <Navbar navigation={navigation}></Navbar>
                {children}
                {myRooms}
            </div>
            <div id={"modal"} className={"fixed top-0 left-0 right-0 z-50 w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full"}>
                <div className={"bg-gray-900 bg-opacity-50 dark:bg-opacity-80 fixed inset-0 z-40"}></div>
            </div>
        </Providers>
        </body>
        </html>
    )
}
